name: Docker Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: cd node && docker build -t robertclaros/storage-service-devopstest:latest .

  newman-test:
    runs-on: ubuntu-latest

    needs: build-docker-image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Newman
      run: npm install -g newman

    - name: Run Newman tests
      run: newman run 'node/Storage Service API.postman_collection.json'

  artillery-test:
    runs-on: ubuntu-latest

    needs: build-docker-image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Artillery tests
      run: |
        $Env:DEBUG="http:response"
        artillery run "api-perf-test.yml"
